// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'views/NavigationView', 'views/MainView', 'Router'], function(Backbone, NavigationView, Router) {
    var app;
    app = {
      regions: {
        navbar: new NavigationView(),
        maincontent: '#maincontent',
        footer: '#footer'
      }
    };
    window.approuter = new Router(app);
    Backbone.history.start({
      pushState: true
    });
    return window.app = app;
  });

}).call(this);
