// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone'], function(Backbone) {
    var app;
    app = {
      regions: {
        navbar: '#navbar',
        maincontent: '#maincontent',
        footer: '#footer'
      }
    };
    return window.app = app;
  });

}).call(this);
