// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'views/NavigationView'], function(Backbone, NavigationView) {
    var app;
    app = {
      regions: {
        navbar: new NavigationView(),
        maincontent: '#maincontent',
        footer: '#footer'
      }
    };
    return window.app = app;
  });

}).call(this);
