// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'views/NavigationView', 'views/MainView'], function(Backbone, NavView, MainView) {
    return Backbone.Router.extend({
      initialize: function(app) {
        return console.log('yo', app);
      },
      routes: {
        'login': 'showLoginView',
        'auth/account': 'showAccountView'
      },
      showLoginView: function() {
        return MainView.show('login');
      },
      showAccountView: function() {}
    });
  });

}).call(this);
