// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'views/NavigationView'], function(Backbone) {
    return Backbone.Router.extend({
      routes: {
        'login': 'showLoginView',
        'auth/account': 'showAccountView'
      },
      showLoginView: function() {},
      showAccountView: function() {}
    });
  });

}).call(this);
