// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'jade!/templates/login'], function(Backbone, Login) {
    return Backbone.View.extend({
      initialize: function() {
        console.log('Loginview');
        return this.$el = $('<div></div>');
      },
      render: function() {
        return this.$el.html(Login());
      }
    });
  });

}).call(this);
