// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'views/LoginView'], function(Backbone, LoginView) {
    return Backbone.View.extend({
      initialize: function() {
        console.log('yo');
        this.$el = $('section#maincontent');
        return this.elems = {
          login: new LoginView()
        };
      },
      show: function(view) {
        this.$el.children().detach();
        this.elems[view].render();
        return this.$el.append(this.elems[view].$el);
      }
    });
  });

}).call(this);
