// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'require-jade'], function(Backbone, Jade) {
    return Backbone.View.extend({
      $el: $('section#navbar'),
      initialize: function() {
        console.log('navbar', this.$el);
        return window.Jade = Jade;
      },
      render: function() {}
    });
  });

}).call(this);
