// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'jade!/templates/navbar'], function(Backbone, Navbar) {
    return Backbone.View.extend({
      initialize: function() {
        console.log('navbar', this.$el);
        this.$el = $('section#navbar');
        return this.render();
      },
      render: function() {
        return this.$el.html(Navbar());
      }
    });
  });

}).call(this);
